### ISSUE TITLE
EU mention

### ISSUE THREAD

**Issue by guydepauw** [benedmo/fact-check-finder#2]
Mention the sponsor 

`Dit project is gefinancierd door de Europese Unie onder overeenkomstnummer: INEA/CEF/ICT/A2020/2381738.`

![eu-img](https://user-images.githubusercontent.com/6727285/196693069-17301add-b19e-4375-a474-ea8cbca801f8.jpg)

**Comment by msramalho** [comment]
updated repo and web store listing (should be approved in the next few days).
